### ISSUE TITLE
"Device Lock Verify Introduction" 的链接为<unknown>

### ISSUE THREAD

**Issue by Integral-Tech** [lomirus/gtk-qq#35]
在Device Lock Verify Introduction界面
提示Please open the link below and use your logged in device [sms:todo] to verify
但是点击下面的Device Lock Verification无反应，点击Copy Link后复制的是```<unknown>```

**Comment by lomirus** [comment]
我这边没有设备锁，不方便调试。先蹲个 link_copier 原作者 @Goodjooy

**Comment by Goodjooy** [comment]
这个似乎是ricq 的 `LoginResponse::DeviceLocked` 没有解析到 verify_url 

目前解决方法暂无

**Comment by Goodjooy** [comment]
好了，现在不会弹出窗口了，如果veirfy url 没拿到的话

**Comment by Integral-Tech** [comment]
> 这个似乎是ricq 的 `LoginResponse::DeviceLocked` 没有解析到 verify_url
> 
> 目前解决方法暂无

所以目前只有关闭设备锁才可以登录吗？

**Comment by Goodjooy** [comment]
> > 这个似乎是ricq 的 `LoginResponse::DeviceLocked` 没有解析到 verify_url
> > 目前解决方法暂无
> 
> 所以目前只有关闭设备锁才可以登录吗？

你可以使用二维码扫码登陆
