### ISSUE TITLE
login response: NeedCaptcha

### ISSUE THREAD

**Issue by K1ngst0m** [lomirus/gtk-qq#6]
when I press the Login button there is no response in GUI, the console message shows `NeedCaptcha` but where can I find it?

![image](https://user-images.githubusercontent.com/34272057/170787220-9f0fb8fe-3b41-4301-8c51-5772f715c3e9.png)

system info:
- wm: bspwm
- distro: gentoo

**Comment by lomirus** [comment]
Fixed in https://github.com/lomirus/gtk-qq/commit/300139ee6a6561def282930a6ab4521e46ad5290

**Comment by rqy1458814497** [comment]
然而在点击链接之后要求拖动滑块完成拼图，但是完成之后似乎无事发生。我仍然无法登录qq。

**Comment by lomirus** [comment]
> 然而在点击链接之后要求拖动滑块完成拼图，但是完成之后似乎无事发生。我仍然无法登录qq。

验证之后再次点击登录的话还是会提示 `NeedCaptcha` 吗？

**Comment by icepie** [comment]
> > 然而在点击链接之后要求拖动滑块完成拼图，但是完成之后似乎无事发生。我仍然无法登录qq。
> 
> 验证之后再次点击登录的话还是会提示 `NeedCaptcha` 吗？

对的 同样的情况

**Comment by rqy1458814497** [comment]
是的，仍然返回NeedCaptcha

**Comment by lomirus** [comment]
原因已找到，是验证码相关接口的响应体中的 ticket 没有使用。

我目前的想法是如果帐号登录需要验证码，就直接弹出一个 webview 并自带 devtool，然后让用户在里面找到发的请求的响应体中的 ticket，然后粘贴回程序弹出的输入框。但问题是这样可能对用户来说有点繁琐，不过目前我也没有想出其他什么简便的获取 ticket 的方法。不知道你们有啥思路没。

**Comment by lomirus** [comment]
还有一种思路是本地跑一个 proxy，然后让用户设置成系统代理，然后程序就可以代理直接拦截到 ticket 了。但问题是设置代理本身也算不上是一个简便的方案。

**Comment by icepie** [comment]
> 

感觉这个方案不太可用，浏览器已经在被打开的情况下，再启动一个新网页貌似不会吃这个环境变量

**Comment by lomirus** [comment]
试了下代理的方案，由于验证码的接口是 https 的，所以前置代理拦截到响应后解析不了数据 😓 这个方案应该是被废弃了

**Comment by rqy1458814497** [comment]
赞美dalao，等我电脑明天修好了就去试）

**Comment by rqy1458814497** [comment]
目前使用正常）
