### ISSUE TITLE
rust依赖

### ISSUE THREAD

**Issue by rqy1458814497** [lomirus/gtk-qq#8]
build这个项目需要rust依赖。但是并没有写到Requirements栏里（

**Comment by lomirus** [comment]
当时主要是觉得一个 rust 项目说要用到 rust 来构建有点多余的样子，所以就没提。不过默认假设所有人都安装了 Rust 的话，确实也不太合适。那我就提一下吧。

**Comment by lomirus** [comment]
Fixed in https://github.com/lomirus/gtk-qq/commit/b905cbcb34b3998929864a6a30320dd4a68d95ab

**Comment by rqy1458814497** [comment]
补充一下，还需要 libssl-dev）

**Comment by lomirus** [comment]
哪个发行版
